### ISSUE TITLE
Update repo and code to use the updated proto file

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/meshery-octarine#15]
**Description**
Recently we have updated the [proto definition](https://github.com/layer5io/meshery/blob/master/meshes/meshops.proto) and hence the generated proto Go [file](https://github.com/layer5io/meshery/blob/master/meshes/meshops.pb.go).

Changes include the following:
- Associate supported ops with categories ([sample](https://github.com/layer5io/meshery-istio/blob/d29c31a950fc3b872beb53d5633e5126930b9a75/istio/supported_ops.go#L24))
- Associate operation id with request and response ([sample method](https://github.com/layer5io/meshery-istio/blob/d29c31a950fc3b872beb53d5633e5126930b9a75/istio/istio.go#L374))

**Comment by leecalcote** [comment]
//@thehh1974

**Comment by leecalcote** [comment]
Done
