### ISSUE TITLE
Add Layer5 Welcome bot to the Meshery adapter for octarine repository

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/meshery-octarine#71]
**Current Behavior**
 A welcome bot has been configured to usher in contributors new to this project. Configuration of this welcome bot is missing from the `meshery-octarine` repository.

**Desired Behavior**
 The [config.yml](https://github.com/layer5io/meshery/blob/master/.github/config.yml) and the [welcome folder](https://github.com/layer5io/meshery/tree/master/.github/welcome) along with the [image](https://github.com/layer5io/meshery/blob/master/.github/welcome/Layer5-celebration.png) inside of it should be copied and placed into the [meshery-octarine repository](https://github.com/layer5io/meshery-octarine/tree/master/.github).

**Comment by Obizim** [comment]
I can take this up
But I've got a question: So, getting the config and welcome folders from the meshery repo and placing it here fixes this issue?

**Comment by Ruth-ikegah** [comment]
Exactly! Making a copy here @Obizim

**Comment by PluckyPrecious** [comment]
Nothing more, nothing less. 😃

**Comment by Obizim** [comment]
Alright✔✔
